char tela_relatorios(void);
void menuRelatorio(void);
char relatorioCliente(void);
char relatorioFuncionario(void);
char relatorioVeiculo(void);
char relatorioAluguel(void);
void listaCliente(void);
void tela_op_cliente(void);
void tela_op_funcionario(void);
void tela_op_aluguel(void);
void tela_op_veiculo(void);
void listaClienteBairro(void);
void listaClienteStatus(char);
void listaFuncionario(void);
void listaFuncionarioBairro(void);
void listaFuncionarioStatus(char);
void listaVeiculo(void);
void listaVeiculoDiaria(void);
void listaVeiculoStatus(char);
void listaAluguel(void);
void listaAluguelData(void);
void listaAluguelStatus(char);
void listaClientesAlfa(void);
void listaFuncionarioAlfa(void);
void listaVeiculoAlfa(void);
char* get_cliente(const char* cpf);
char *get_veiculo(const char* placa);