int validadorNome(char*);
int validadorModelo(char*);
int validadorFabricante(char*);
int validadorPlaca(char*);
int validadorChassi(char*);
int validadorTelefone(char*);
int validadorCPF(char*);
int validadorData(int, int, int);
int validadorCidade(char*);
int validadorCargo(char*);
int validadorDiaria(int);
int validadorConservacao(char*);
int ano_bissexto(int);  
int validadorAno(int);
void limpaBuffer(void);